# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1323, 614)
        MainWindow.setStyleSheet("QLabel{\n"
"    background-color:white;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.left_image = QtWidgets.QLabel(self.centralwidget)
        self.left_image.setGeometry(QtCore.QRect(10, 100, 640, 480))
        self.left_image.setObjectName("left_image")
        self.right_image = QtWidgets.QLabel(self.centralwidget)
        self.right_image.setGeometry(QtCore.QRect(670, 100, 640, 480))
        self.right_image.setObjectName("right_image")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(320, 70, 681, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(650, 100, 20, 481))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.btnOpen = QtWidgets.QPushButton(self.centralwidget)
        self.btnOpen.setGeometry(QtCore.QRect(490, 40, 99, 28))
        self.btnOpen.setObjectName("btnOpen")
        self.btnDetect = QtWidgets.QPushButton(self.centralwidget)
        self.btnDetect.setGeometry(QtCore.QRect(610, 40, 93, 28))
        self.btnDetect.setObjectName("btnDetect")
        self.btnStandard = QtWidgets.QPushButton(self.centralwidget)
        self.btnStandard.setGeometry(QtCore.QRect(720, 40, 151, 28))
        self.btnStandard.setObjectName("btnStandard")
        self.btnMeasure = QtWidgets.QPushButton(self.centralwidget)
        self.btnMeasure.setGeometry(QtCore.QRect(890, 40, 93, 28))
        self.btnMeasure.setObjectName("btnMeasure")
        self.btnScanCam = QtWidgets.QPushButton(self.centralwidget)
        self.btnScanCam.setGeometry(QtCore.QRect(372, 40, 101, 28))
        self.btnScanCam.setObjectName("btnScanCam")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.ActCam = QtWidgets.QAction(MainWindow)
        self.ActCam.setObjectName("ActCam")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.left_image.setText(_translate("MainWindow", "左摄像头图像"))
        self.right_image.setText(_translate("MainWindow", "右摄像头图像"))
        self.btnOpen.setText(_translate("MainWindow", "打开双目相机"))
        self.btnDetect.setText(_translate("MainWindow", "目标检测"))
        self.btnStandard.setText(_translate("MainWindow", "相机标定与图像采集"))
        self.btnMeasure.setText(_translate("MainWindow", "双目测距"))
        self.btnScanCam.setText(_translate("MainWindow", "检测双目相机"))
        self.ActCam.setText(_translate("MainWindow", "测试相机"))
